# Generated by Django 3.0.6 on 2020-07-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tile',
            new_name='time',
        ),
    ]
