# Generated by Django 3.0.6 on 2020-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('explain', models.TextField(default='explain.')),
                ('pic', models.ImageField(blank=True, upload_to='image')),
                ('day', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
