# Generated by Django 3.0.6 on 2020-06-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picedit',
            old_name='text',
            new_name='title',
        ),
    ]
