# Generated by Django 3.0.6 on 2020-06-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0002_auto_20200629_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picedit',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
