# Generated by Django 3.0.6 on 2020-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0003_auto_20200630_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picedit',
            name='pic',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
