# Generated by Django 3.0.6 on 2020-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0004_auto_20200704_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picedit',
            name='explain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='picedit',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
