# Generated by Django 2.0.7 on 2020-10-12 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='plan',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
