# Generated by Django 3.0.8 on 2020-08-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='melonList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(max_length=100)),
                ('singerName', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('imgSrc', models.TextField(blank=True)),
            ],
        ),
    ]
