# Generated by Django 3.0.6 on 2020-06-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('memberId', models.IntegerField(primary_key=True, serialize=False)),
                ('memberName', models.CharField(max_length=123)),
                ('home', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('memberId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Members')),
            ],
        ),
    ]
