# Generated by Django 3.0.6 on 2020-06-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('productName', models.CharField(max_length=50)),
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sheets',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('contents1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Members')),
                ('contents2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Orders')),
                ('contents3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Goods')),
            ],
        ),
    ]
