# Generated by Django 3.0.6 on 2020-05-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prac',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='prac',
            name='prefer',
        ),
        migrations.AddField(
            model_name='prac',
            name='new',
            field=models.FileField(default='', max_length=3000, upload_to=''),
        ),
        migrations.AddField(
            model_name='prac',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='prac',
            name='channel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
